import { StyleSheet, Dimensions, Platform } from "react-native";

const { width, height } = Dimensions.get("window");

const isMobile = width < 768;
const isTablet = width >= 768 && width < 1024;
const isDesktop = width >= 1024;

export const CitizenStyles = StyleSheet.create({
 
  container: {
    flex: 1,
    backgroundColor: '#FAFBFC',
  },
  containerDark: {
    backgroundColor: '#0A0B0E',
  },

  featureModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  featureModalContainer: {
    width: isMobile ? '100%' : width * 0.6,
    maxWidth: 500,
    height: isMobile ? '80%' : '70%',
    maxHeight: 600,
    borderRadius: 24,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 20,
  },
  featureModalBlurView: {
    flex: 1,
  },
  featureModalGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  featureModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 107, 53, 0.15)',
  },
  featureModalTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  featureModalIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 107, 53, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    borderWidth: 2,
    borderColor: 'rgba(255, 107, 53, 0.2)',
  },
  featureModalIconContainerDark: {
    backgroundColor: 'rgba(255, 107, 53, 0.2)',
    borderColor: 'rgba(255, 107, 53, 0.3)',
  },
  featureModalIcon: {
    fontSize: 20,
  },
  featureModalTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#1A202C',
    fontFamily: 'Inter_800ExtraBold',
    flex: 1,
  },
  featureModalTitleDark: {
    color: '#FFFFFF',
  },
  featureModalCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 107, 53, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 12,
  },
  featureModalCloseIcon: {
    fontSize: 18,
    color: '#FF6B35',
    fontWeight: '600',
  },
  featureModalCloseIconDark: {
    color: '#FF6B35',
  },
  featureModalContent: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 20,
  },
  featureModalStats: {
    backgroundColor: 'rgba(255, 107, 53, 0.08)',
    padding: 12,
    borderRadius: 12,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 107, 53, 0.15)',
  },
  featureModalStatsText: {
    fontSize: 14,
    color: '#FF6B35',
    fontWeight: '600',
    fontFamily: 'Inter_600SemiBold',
    textAlign: 'center',
  },
  featureModalStatsTextDark: {
    color: '#FF6B35',
  },
  featureModalDescription: {
    fontSize: 16,
    color: '#4A5568',
    lineHeight: 24,
    fontFamily: 'Inter_500Medium',
    marginBottom: 24,
  },
  featureModalDescriptionDark: {
    color: 'rgba(255, 255, 255, 0.9)',
  },
  featureModalBenefits: {
    marginBottom: 20,
  },
  featureModalBenefitsTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1A202C',
    fontFamily: 'Inter_700Bold',
    marginBottom: 12,
  },
  featureModalBenefitsTitleDark: {
    color: '#FFFFFF',
  },
  featureModalBenefitsList: {
    gap: 10,
  },
  featureModalBenefitItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 107, 53, 0.05)',
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 107, 53, 0.1)',
  },
  featureModalBenefitItemDark: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderColor: 'rgba(255, 107, 53, 0.15)',
  },
  featureModalBenefitIcon: {
    fontSize: 16,
    color: '#FF6B35',
    marginRight: 10,
    fontWeight: '700',
  },
  featureModalBenefitText: {
    fontSize: 14,
    color: '#4A5568',
    fontFamily: 'Inter_500Medium',
    flex: 1,
  },
  featureModalBenefitTextDark: {
    color: 'rgba(255, 255, 255, 0.9)',
  },
  featureModalFooter: {
    paddingHorizontal: 24,
    paddingBottom: 24,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 107, 53, 0.15)',
  },
  featureModalButton: {
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#FF6B35',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 8,
  },
  featureModalButtonDark: {
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  featureModalButtonGradient: {
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 16,
  },
  featureModalButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
    fontFamily: 'Inter_700Bold',
    textAlign: 'center',
    letterSpacing: 0.5,
  },

  // Menu Styles
  menuBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },
  menuContainer: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    width: width * 0.65,
  },
  menuBlurView: {
    flex: 1,
  },
  menuGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  menuHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 107, 53, 0.15)',
  },
  menuTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#1A202C',
    fontFamily: 'Inter_800ExtraBold',
  },
  menuTitleDark: {
    color: '#FFFFFF',
  },
  menuCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 107, 53, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuCloseIcon: {
    fontSize: 18,
    color: '#FF6B35',
    fontWeight: '600',
  },
  menuCloseIconDark: {
    color: '#FF6B35',
  },
  menuItems: {
    paddingTop: 20,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 20,
    marginHorizontal: 12,
    marginBottom: 6,
    borderRadius: 12,
  },
  menuItemActive: {
    backgroundColor: 'rgba(255, 107, 53, 0.12)',
    borderLeftWidth: 4,
    borderLeftColor: '#FF6B35',
  },
  menuItemLogout: {
    marginTop: 10,
    backgroundColor: 'rgba(239, 68, 68, 0.12)',
    borderLeftWidth: 4,
    borderLeftColor: '#EF4444',
  },
  menuIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 107, 53, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  menuIconActive: {
    backgroundColor: '#FF6B35',
  },
  menuIconLogout: {
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
  },
  menuIcon: {
    fontSize: 18,
    color: '#FF6B35',
  },
  menuIconDark: {
    color: '#FF6B35',
  },
  menuIconLogoutText: {
    fontSize: 18,
    color: '#EF4444',
  },
  menuItemText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#4A5568',
    fontFamily: 'Inter_600SemiBold',
  },
  menuItemTextDark: {
    color: 'rgba(255, 255, 255, 0.9)',
  },
  menuItemTextActive: {
    color: '#FF6B35',
    fontWeight: '700',
  },
  menuItemTextLogout: {
    color: '#EF4444',
    fontWeight: '700',
  },
  menuFooter: {
    position: 'absolute',
    bottom: 30,
    left: 20,
    right: 20,
  },
  menuFooterText: {
    fontSize: 11,
    color: '#718096',
    textAlign: 'center',
    fontFamily: 'Inter_500Medium',
  },
  menuFooterTextDark: {
    color: 'rgba(255, 255, 255, 0.6)',
  },

  // ScrollView content
  scrollViewContent: {
    paddingTop: 140,
    paddingBottom: 100,
  },

  // Section Header
  sectionHeaderContainer: {
    paddingHorizontal: 24,
    marginTop: 15,
    marginBottom: 15,
  },
  sectionHeaderContent: {
    flex: 1,
  },
  sectionHeaderTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: '#1A202C',
    fontFamily: 'Inter_800ExtraBold',
    marginBottom: 4,
  },
  sectionHeaderTitleDark: {
    color: '#FFFFFF',
  },
  sectionHeaderSubtitle: {
    fontSize: 16,
    color: '#718096',
    fontWeight: '500',
    fontFamily: 'Inter_500Medium',
  },
  sectionHeaderSubtitleDark: {
    color: 'rgba(255, 255, 255, 0.7)',
  },
  sectionHeaderIcon: {
    position: 'absolute',
    right: 24,
    top: 0,
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(255, 107, 53, 0.12)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255, 107, 53, 0.2)',
  },
  sectionHeaderIconText: {
    fontSize: 24,
  },

  // Enhanced Header Section
  headerSection: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 1000,
    paddingTop: Platform.OS === 'ios' ? 60 : 40,
    paddingBottom: 20,
    paddingHorizontal: 24,
    overflow: 'hidden',
    minHeight: 140,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 10,
  },
  headerSectionDark: {
    backgroundColor: 'rgba(26, 21, 18, 0.95)',
    shadowColor: '#FF6B35',
    shadowOpacity: 0.2,
    shadowRadius: 20,
  },
  headerGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#FF6B35',
  },
  headerGradientDark: {
    backgroundColor: 'rgba(139, 69, 19, 0.8)',
  },
  headerPattern: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  headerPatternDot: {
    position: 'absolute',
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
  },
  headerPatternDotDark: {
    backgroundColor: 'rgba(255, 107, 53, 0.2)',
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    zIndex: 1,
  },
  welcomeContainer: {
    flex: 1,
  },
  welcomeText: {
    fontSize: 14,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.95)',
    fontFamily: 'Inter_600SemiBold',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 4,
  },
  welcomeTextDark: {
    color: 'rgba(255, 255, 255, 0.9)',
  },
  welcomeName: {
    fontSize: 32,
    fontWeight: '800',
    color: '#FFFFFF',
    fontFamily: 'Inter_800ExtraBold',
    marginBottom: 6,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  welcomeSubtitle: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.85)',
    fontWeight: '500',
    fontFamily: 'Inter_500Medium',
  },
  welcomeSubtitleDark: {
    color: 'rgba(255, 255, 255, 0.7)',
  },
  headerControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    paddingTop: 4,
  },
  darkModeToggle: {
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  darkModeToggleActive: {
    backgroundColor: 'rgba(139, 69, 19, 0.3)',
    borderColor: 'rgba(255, 107, 53, 0.4)',
  },
  toggleKnob: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  toggleKnobActive: {
    backgroundColor: '#FFA235',
  },
  toggleIcon: {
    fontSize: 16,
  },
  toggleText: {
    fontSize: 11,
    color: 'white',
    fontWeight: '600',
    fontFamily: 'Inter_600SemiBold',
  },
  toggleTextDark: {
    color: '#FFDAB9',
  },
  menuButton: {
    width: 48,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  menuButtonDark: {
    backgroundColor: 'rgba(139, 69, 19, 0.3)',
    borderColor: 'rgba(255, 107, 53, 0.4)',
  },
  menuLine: {
    height: 3,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 2,
    marginVertical: 2,
    width: 24,
  },
  menuLineDark: {
    backgroundColor: '#FFDAB9',
  },

  // Hero Mission Section
  heroSection: {
    minHeight: 420,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 50,
    position: 'relative',
    overflow: 'hidden',
    marginVertical: 25,
    marginHorizontal: 20,
    borderRadius: 32,
    borderWidth: 2,
    borderColor: 'rgba(255, 107, 53, 0.15)',
    backgroundColor: 'white',
    shadowColor: '#FF6B35',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.15,
    shadowRadius: 30,
    elevation: 15,
  },
  heroSectionDark: {
    backgroundColor: 'rgba(26, 21, 18, 0.95)',
    borderColor: 'rgba(255, 107, 53, 0.25)',
    shadowColor: '#FF6B35',
    shadowOpacity: 0.2,
    shadowRadius: 25,
  },
  heroBackgroundImage: {
    position: 'absolute',
    width: '140%',
    height: '140%',
    opacity: 0.08,
  },
  heroBackgroundImageDark: {
    opacity: 0.05,
  },
  heroOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  heroOverlayDark: {
    backgroundColor: 'rgba(26, 21, 18, 0.6)',
  },
  heroParticlesContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  heroParticle: {
    position: 'absolute',
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  heroParticleLight: {
    backgroundColor: 'rgba(255, 107, 53, 0.3)',
  },
  heroParticleDark: {
    backgroundColor: 'rgba(255, 107, 53, 0.4)',
    shadowColor: '#FF6B35',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  heroContent: {
    alignItems: 'center',
    paddingVertical: 40,
    width: '100%',
  },
  missionIconContainer: {
    width: 100,
    height: 100,
    borderRadius: 50,
    marginBottom: 30,
    position: 'relative',
  },
  missionIconGradient: {
    width: '100%',
    height: '100%',
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  missionIconInner: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  missionIconGlow: {
    position: 'absolute',
    top: -10,
    left: -10,
    right: -10,
    bottom: -10,
    borderRadius: 60,
    backgroundColor: 'rgba(255, 107, 53, 0.15)',
    zIndex: -1,
  },
  missionEmoji: {
    fontSize: 40,
  },
  missionTextContainer: {
    alignItems: 'center',
    marginBottom: 30,
    paddingHorizontal: 20,
  },
  missionTagline: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FF6B35',
    fontFamily: 'Inter_700Bold',
    textTransform: 'uppercase',
    letterSpacing: 2,
    marginBottom: 12,
  },
  missionTaglineDark: {
    color: '#FF6B35',
  },
  missionText: {
    fontSize: 28,
    fontWeight: '700',
    color: '#1A202C',
    textAlign: 'center',
    lineHeight: 38,
    fontFamily: 'Inter_700Bold',
  },
  missionTextDark: {
    color: '#FFFFFF',
    textShadowColor: 'rgba(255, 107, 53, 0.3)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  missionAccent: {
    color: '#FF6B35',
    fontFamily: 'Inter_800ExtraBold',
    fontSize: 30,
  },
  missionStats: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 107, 53, 0.08)',
    padding: 20,
    borderRadius: 24,
    marginBottom: 30,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 107, 53, 0.15)',
  },
  missionStatsDark: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  heroStatItem: {
    alignItems: 'center',
    paddingHorizontal: 15,
  },
  statDivider: {
    width: 1,
    backgroundColor: 'rgba(255, 107, 53, 0.2)',
    marginHorizontal: 10,
  },
  heroStatNumber: {
    fontSize: 22,
    fontWeight: '800',
    color: '#FF6B35',
    fontFamily: 'Inter_800ExtraBold',
  },
  heroStatNumberDark: {
    color: '#FF6B35',
  },
  heroStatLabel: {
    fontSize: 12,
    color: '#718096',
    fontWeight: '600',
    fontFamily: 'Inter_600SemiBold',
    marginTop: 6,
  },
  heroStatLabelDark: {
    color: 'rgba(255, 255, 255, 0.8)',
  },
  heroCTA: {
    backgroundColor: 'rgba(255, 107, 53, 0.1)',
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: 'rgba(255, 107, 53, 0.2)',
  },
  heroCTADark: {
    backgroundColor: 'rgba(255, 107, 53, 0.15)',
    borderColor: 'rgba(255, 107, 53, 0.3)',
  },
  heroCTAText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FF6B35',
    fontFamily: 'Inter_600SemiBold',
  },

  // Enhanced Card Container Styles
  enhancedCardContainer: {
    marginHorizontal: 20,
    marginVertical: 15,
    borderRadius: 24,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 15,
    borderWidth: 1,
    borderColor: 'rgba(255, 107, 53, 0.15)',
    position: 'relative',
  },
  enhancedCardContainerDark: {
    backgroundColor: 'rgba(30, 30, 30, 0.95)',
    shadowColor: '#FF6B35',
    shadowOpacity: 0.1,
    shadowRadius: 15,
    borderColor: 'rgba(255, 107, 53, 0.25)',
  },
  enhancedCardGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  cardPatternOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  cardPatternCircle: {
    position: 'absolute',
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: 'rgba(255, 107, 53, 0.03)',
  },
  cardPatternCircleDark: {
    backgroundColor: 'rgba(255, 107, 53, 0.05)',
  },
  cardBorderGlow: {
    position: 'absolute',
    top: 1,
    left: 1,
    right: 1,
    bottom: 1,
    borderRadius: 23,
    opacity: 0.15,
  },
  enhancedCardContent: {
    padding: 24,
    zIndex: 2,
  },
  enhancedCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  enhancedCardBadge: {
    backgroundColor: 'rgba(255, 107, 53, 0.12)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 107, 53, 0.2)',
  },
  enhancedCardBadgeDark: {
    backgroundColor: 'rgba(255, 107, 53, 0.2)',
    borderColor: 'rgba(255, 107, 53, 0.3)',
  },
  enhancedCardBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FF6B35',
    fontFamily: 'Inter_700Bold',
    letterSpacing: 0.5,
  },
  enhancedCardIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    overflow: 'hidden',
    shadowColor: '#FF6B35',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  enhancedCardIconGradient: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  enhancedCardMain: {
    marginBottom: 24,
  },
  enhancedCardTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#1A202C',
    fontFamily: 'Inter_800ExtraBold',
    marginBottom: 12,
    lineHeight: 32,
  },
  enhancedCardTitleDark: {
    color: '#FFFFFF',
  },
  enhancedCardDescription: {
    fontSize: 15,
    color: '#718096',
    lineHeight: 24,
    fontFamily: 'Inter_500Medium',
    marginBottom: 20,
  },
  enhancedCardDescriptionDark: {
    color: 'rgba(255, 255, 255, 0.8)',
  },
  enhancedFeaturesRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  enhancedFeature: {
    flex: 1,
    alignItems: 'center',
    padding: 12,
    backgroundColor: 'rgba(255, 107, 53, 0.08)',
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 107, 53, 0.15)',
  },
  enhancedFeatureDark: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  enhancedFeatureIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 107, 53, 0.12)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 107, 53, 0.2)',
  },
  enhancedFeatureIconDark: {
    backgroundColor: 'rgba(255, 107, 53, 0.2)',
    borderColor: 'rgba(255, 107, 53, 0.3)',
  },
  enhancedFeatureIconText: {
    fontSize: 16,
  },
  enhancedFeatureLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#4A5568',
    fontFamily: 'Inter_600SemiBold',
    textAlign: 'center',
  },
  enhancedFeatureLabelDark: {
    color: 'rgba(255, 255, 255, 0.9)',
  },
  enhancedStatsBar: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 107, 53, 0.08)',
    padding: 16,
    borderRadius: 16,
    marginBottom: 20,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 107, 53, 0.15)',
  },
  enhancedStatsBarDark: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  enhancedStatItem: {
    flex: 1,
    alignItems: 'center',
  },
  enhancedStatDivider: {
    width: 1,
    backgroundColor: 'rgba(255, 107, 53, 0.2)',
    marginHorizontal: 8,
  },
  enhancedStatNumber: {
    fontSize: 20,
    fontWeight: '800',
    color: '#FF6B35',
    fontFamily: 'Inter_800ExtraBold',
    marginBottom: 4,
  },
  enhancedStatNumberDark: {
    color: '#FF6B35',
  },
  enhancedStatLabel: {
    fontSize: 12,
    color: '#718096',
    fontWeight: '600',
    fontFamily: 'Inter_600SemiBold',
  },
  enhancedStatLabelDark: {
    color: 'rgba(255, 255, 255, 0.8)',
  },
  enhancedActionButton: {
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#FF6B35',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 15,
    elevation: 10,
    marginBottom: 16,
  },
  enhancedActionButtonDark: {
    shadowOpacity: 0.3,
    shadowRadius: 12,
  },
  enhancedActionButtonGradient: {
    paddingVertical: 18,
    paddingHorizontal: 24,
    borderRadius: 16,
  },
  enhancedActionButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  enhancedActionButtonText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
    fontFamily: 'Inter_700Bold',
    marginRight: 12,
    letterSpacing: 0.5,
  },
  enhancedActionButtonIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  enhancedActionButtonIconText: {
    fontSize: 16,
    color: '#FFFFFF',
  },
  enhancedCardFooter: {
    fontSize: 13,
    color: '#718096',
    textAlign: 'center',
    fontFamily: 'Inter_500Medium',
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 107, 53, 0.15)',
  },
  enhancedCardFooterDark: {
    color: 'rgba(255, 255, 255, 0.7)',
    borderTopColor: 'rgba(255, 255, 255, 0.1)',
  },

  featuresSectionWithImage: {
    marginHorizontal: 0, 
    marginVertical: 10,
    borderRadius: 28,
    overflow: 'hidden',
    position: 'relative',
    minHeight: isMobile ? 500 : 320,
    marginBottom: 30,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
    elevation: 10,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 107, 53, 0.15)',
    flexDirection: isMobile ? 'column' : 'row',
  },
  featuresSectionWithImageDark: {
    backgroundColor: '#0A0B0E',
    borderColor: 'rgba(255, 107, 53, 0.25)',
    shadowColor: '#FF6B35',
    shadowOpacity: 0.1,
    shadowRadius: 25,
  },
  
  featuresLeftColumn: {
    flex: isMobile ? undefined : 1.2,
    width: isMobile ? '100%' : 'auto',
    height: isMobile ? 220 : 'auto',
    padding: isMobile ? 16 : 20, 
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
    position: 'relative',
    zIndex: 2,
  },
  featuresImageWrapper: {
    width: isMobile ? '90%' : '100%',
    height: isMobile ? 180 : '100%',
    borderRadius: 20,
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 8,
    borderWidth: 3,
    borderColor: 'rgba(255, 255, 255, 0.9)',
  },
  featuresImageWrapperDark: {
    borderColor: 'rgba(255, 107, 53, 0.15)',
  },
  featuresImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  
  featuresRightColumn: {
    flex: isMobile ? undefined : 1.8,
    width: isMobile ? '100%' : 'auto',
    position: 'relative',
    paddingTop: isMobile ? 16 : 20, 
    paddingBottom: isMobile ? 16 : 20, 
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  featuresRightColumnDark: {
    backgroundColor: 'transparent',
  },
  featuresBackgroundImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
    opacity: isMobile ? 0.1 : 0.15,
  },
  
  featuresHeader: {
    marginBottom: isMobile ? 16 : 20,
    paddingHorizontal: isMobile ? 16 : 24, 
  },
  featuresTagline: {
    fontSize: isMobile ? 12 : 14,
    fontWeight: '600',
    color: '#FF6B35',
    fontFamily: 'Inter_600SemiBold',
    textTransform: 'uppercase',
    letterSpacing: isMobile ? 1.5 : 2,
    marginBottom: isMobile ? 6 : 8,
  },
  featuresTitle: {
    fontSize: isMobile ? 22 : 26,
    fontWeight: '800',
    color: '#1A202C',
    fontFamily: 'Inter_800ExtraBold',
    marginBottom: isMobile ? 10 : 12,
    lineHeight: isMobile ? 28 : 32,
  },
  featuresTitleDark: {
    color: '#FFFFFF',
  },
  featuresSubtitle: {
    fontSize: isMobile ? 14 : 15,
    color: '#718096',
    lineHeight: isMobile ? 20 : 22,
    fontWeight: '500',
    fontFamily: 'Inter_500Medium',
    marginBottom: isMobile ? 6 : 8,
  },
  featuresSubtitleDark: {
    color: 'rgba(255, 255, 255, 0.8)',
  },
  
  featuresContentGrid: {
    gap: isMobile ? 12 : 16,
    paddingHorizontal: 0, 
  },
  
  featuresContentItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
    borderRadius: 0, 
    padding: isMobile ? 16 : 20,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 107, 53, 0.1)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    marginHorizontal: 0, 
    width: '100%', 
    marginBottom: isMobile ? 1 : 1, 
    borderLeftWidth: 0,
    borderRightWidth: 0, 
    borderTopWidth: 1.5,
    borderBottomWidth: 1.5,
  },
  featuresContentItemDark: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderColor: 'rgba(255, 107, 53, 0.15)',
  },
  
  featuresContentItemHovered: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    borderRadius: 0, 
    padding: isMobile ? 16 : 20,
    borderWidth: 2,
    borderColor: 'rgba(255, 107, 53, 0.3)',
    shadowColor: '#FF6B35',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 6,
    transform: [{ translateY: -3 }],
    marginHorizontal: 0,
    width: '100%', 
    marginBottom: isMobile ? 1 : 1, 
    borderLeftWidth: 0, 
    borderRightWidth: 0, 
    borderTopWidth: 2,
    borderBottomWidth: 2,
  },
  featuresContentItemHoveredDark: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderColor: 'rgba(255, 107, 53, 0.4)',
    shadowColor: '#FF6B35',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
  },
  
  featuresContentIconContainer: {
    width: isMobile ? 44 : 48,
    height: isMobile ? 44 : 48,
    borderRadius: isMobile ? 22 : 24,
    backgroundColor: 'rgba(255, 107, 53, 0.12)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: isMobile ? 14 : 16,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 107, 53, 0.2)',
    shadowColor: '#FF6B35',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  featuresContentIconContainerDark: {
    backgroundColor: 'rgba(255, 107, 53, 0.2)',
    borderColor: 'rgba(255, 107, 53, 0.3)',
  },
  featuresContentIcon: {
    fontSize: isMobile ? 18 : 20,
  },
  featuresContentTextContainer: {
    flex: 1,
  },
  featuresContentTitle: {
    fontSize: isMobile ? 16 : 17,
    fontWeight: '700',
    color: '#1A202C',
    fontFamily: 'Inter_700Bold',
    marginBottom: isMobile ? 4 : 6,
  },
  featuresContentTitleDark: {
    color: '#FFFFFF',
  },
  featuresContentDescription: {
    fontSize: isMobile ? 13 : 14,
    color: '#718096',
    lineHeight: isMobile ? 18 : 20,
    fontWeight: '500',
    fontFamily: 'Inter_500Medium',
  },
  featuresContentDescriptionDark: {
    color: 'rgba(255, 255, 255, 0.8)',
  },
  
  // Features Stats
  featuresStats: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: isMobile ? 20 : 24,
    paddingTop: isMobile ? 16 : 20,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 107, 53, 0.15)',
  },
  featuresStatItem: {
    alignItems: 'center',
    flex: 1,
  },
  featuresStatNumber: {
    fontSize: isMobile ? 18 : 20,
    fontWeight: '800',
    color: '#FF6B35',
    fontFamily: 'Inter_800ExtraBold',
    marginBottom: isMobile ? 3 : 4,
  },
  featuresStatLabel: {
    fontSize: isMobile ? 11 : 12,
    color: '#718096',
    fontWeight: '600',
    fontFamily: 'Inter_600SemiBold',
    textAlign: 'center',
  },
  featuresStatLabelDark: {
    color: 'rgba(255, 255, 255, 0.7)',
  },
  featuresStatDivider: {
    width: 1,
    height: 30,
    backgroundColor: 'rgba(255, 107, 53, 0.2)',
  },

  // Community Stats Section
  statsSection: {
    marginHorizontal: 20,
    marginVertical: 10,
    marginBottom: 30,
    borderRadius: 28,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 10,
  },
  statsSectionDark: {
    shadowColor: '#FF6B35',
    shadowOpacity: 0.1,
  },
  statsGradient: {
    padding: 24,
    borderRadius: 28,
  },
  statsGradientDark: {
    backgroundColor: 'rgba(26, 21, 18, 0.9)',
  },
  statsBackgroundShade: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 107, 53, 0.03)',
    borderRadius: 28,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 12,
  },
  statsCard: {
    width: (width - 88) / 2 - 6,
    alignItems: 'center',
    paddingVertical: 20,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 20,
    borderWidth: 2,
    borderColor: 'rgba(255, 107, 53, 0.15)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    marginBottom: 12,
  },
  statsCardDark: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderColor: 'rgba(255, 107, 53, 0.15)',
  },
  statsIconContainer: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(255, 107, 53, 0.12)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    borderWidth: 2,
    borderColor: 'rgba(255, 107, 53, 0.2)',
  },
  statsIconContainerDark: {
    backgroundColor: 'rgba(255, 107, 53, 0.12)',
    borderColor: 'rgba(255, 107, 53, 0.2)',
  },
  statsIcon: {
    fontSize: 24,
  },
  statsNumber: {
    fontSize: 28,
    fontWeight: '800',
    color: '#FF6B35',
    fontFamily: 'Inter_800ExtraBold',
    marginBottom: 6,
  },
  statsNumberDark: {
    color: '#FF6B35',
  },
  statsLabel: {
    fontSize: 14,
    color: '#718096',
    fontWeight: '600',
    fontFamily: 'Inter_600SemiBold',
    textAlign: 'center',
  },
  statsLabelDark: {
    color: 'rgba(255, 255, 255, 0.8)',
  },
  statsFooter: {
    marginTop: 20,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 107, 53, 0.2)',
    alignItems: 'center',
  },
  statsFooterDark: {
    borderTopColor: 'rgba(255, 107, 53, 0.2)',
  },
  statsFooterText: {
    fontSize: 14,
    color: '#718096',
    fontWeight: '500',
    fontFamily: 'Inter_500Medium',
    textAlign: 'center',
  },
  statsFooterTextDark: {
    color: 'rgba(255, 255, 255, 0.7)',
  },

  // Bottom Navigation
  navBarBlur: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 107, 53, 0.1)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -6 },
    shadowOpacity: 0.1,
    shadowRadius: 15,
    elevation: 12,
  },
  navBar: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingVertical: 12,
    paddingBottom: Platform.OS === 'ios' ? 34 : 12,
  },
  navBarDark: {
    backgroundColor: 'rgba(10, 11, 14, 0.95)',
    borderTopColor: 'rgba(255, 107, 53, 0.15)',
  },
  navItem: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 8,
  },
  navIconContainer: {
    width: 52,
    height: 52,
    borderRadius: 26,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
  },
  navIconContainerInactive: {
    backgroundColor: 'rgba(255, 107, 53, 0.08)',
  },
  navIconContainerActive: {
    backgroundColor: 'transparent',
    position: 'relative',
    top: -8,
  },
  navIconGradient: {
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#FF6B35',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 10,
  },
  navIcon: {
    fontSize: 20,
  },
  navIconActive: {
    color: 'white',
  },
  navIconInactive: {
    color: '#718096',
  },
  navText: {
    fontSize: 11,
    fontWeight: '700',
    fontFamily: 'Inter_700Bold',
    marginTop: 2,
    letterSpacing: 0.5,
  },
  navTextActive: {
    color: '#FF6B35',
    marginTop: -4,
    fontWeight: '800',
    fontSize: 12,
  },
  navTextInactive: {
    color: '#718096',
  },

  // Card Features Grid
  cardFeaturesGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
    paddingHorizontal: 4,
  },
  featureBox: {
    alignItems: 'center',
    flex: 1,
    paddingHorizontal: 6,
  },
  featureIconBox: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(255, 107, 53, 0.12)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    borderWidth: 2,
    borderColor: 'rgba(255, 107, 53, 0.2)',
  },
  featureIconBoxDark: {
    backgroundColor: 'rgba(255, 107, 53, 0.15)',
    borderColor: 'rgba(255, 107, 53, 0.3)',
  },
  featureIcon: {
    fontSize: 18,
    color: '#FF6B35',
  },
  featureLabel: {
    fontSize: 12,
    color: '#4A5568',
    fontWeight: '600',
    fontFamily: 'Inter_600SemiBold',
  },
  featureLabelDark: {
    color: 'rgba(255, 255, 255, 0.9)',
  },

  // Stats Row
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
    paddingHorizontal: 8,
    backgroundColor: 'rgba(255, 107, 53, 0.08)',
    borderRadius: 16,
    paddingVertical: 12,
    alignItems: 'center',
  },
  statsRowDark: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  statBox: {
    alignItems: 'center',
    flex: 1,
  },
  statDividerVertical: {
    width: 1,
    height: 30,
    backgroundColor: 'rgba(255, 107, 53, 0.2)',
  },
  cardStatNumber: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1A202C',
    fontFamily: 'Inter_800ExtraBold',
    marginBottom: 2,
  },
  cardStatNumberDark: {
    color: '#FFFFFF',
  },
  cardStatLabel: {
    fontSize: 11,
    color: '#718096',
    fontWeight: '500',
    fontFamily: 'Inter_500Medium',
    textAlign: 'center',
    lineHeight: 14,
  },
  cardStatLabelDark: {
    color: 'rgba(255, 255, 255, 0.7)',
  },

  // Button Wrapper
  buttonWrapper: {
    marginTop: 0,
  },

  // Enhanced Button
  submitButton: {
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#FF6B35',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 8,
  },
  submitButtonDark: {
    shadowColor: '#FF6B35',
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  buttonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 16,
    backgroundColor: '#FF6B35',
  },
  buttonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
    fontFamily: 'Inter_700Bold',
    marginRight: 10,
    letterSpacing: 0.5,
  },
  buttonIconContainer: {
    marginLeft: 4,
  },
  buttonIcon: {
    color: 'white',
    fontSize: 18,
    fontWeight: '700',
  },
});

export const CitizenAnimations = {
  fadeIn: {
    opacity: [0, 1],
    scale: [0.9, 1],
  },
  slideUp: {
    translateY: [50, 0],
    opacity: [0, 1],
  },
  pulse: {
    scale: [1, 1.08, 1],
  },
  bounce: {
    translateY: [0, -8, 0],
  },
  float: {
    translateY: [0, -15, 0],
  },
};